include parallelDefs

# required files
SORT = blockRadixSort.h transpose.h
GLOBAL_REQUIRE = parallel.h sequence.h $(SORT)
LOCAL_REQUIRE = 
INCLUDE = blockRadixSort.h

include ../common/timeRequiredFiles
include MakeBenchI
